# Provide either GitHub versions or local paths to the top directory of each
# if the pipelines are directly in the current directory, use "./" at the beginning

pipeline_versions:
  imputePipeline: b40c3521634334c801ed3381769ee8146b049f96
  # postImpute: /some/local/path

indir: "/some/directory"
datasets:
  # BioMe_array-regeneron_GSA:
  #    infile: '{indir}/regeneron_GSA_hg19.bed'
  #    build: hg19
  #    filters: '--chr 17'
  #    impute: False
  # BioMe_array-sema4_GDA:
  #    infile: '{indir}/sema4_GDA_hg19.bed'
  #    build: hg19
  #    filters: '--chr 17'
  #    impute: False
  # NYSCF_array:
  #    infile: input/NYSCF_MSSM_Chr17.ped
  #    build: hg19
  #    impute: True
  # test_vcf:
  #    infile: input/test.vcf.gz
  #    build: hg38
  # ADSP-WGS-r4:
  #   infile: /sc/arion/projects/load/data-ext/ADSP/ADSP_Umbrella_ng00067.v10/geno/gcad.qc.compact_filtered.r4.wgs.36361.GATK.2023.06.06.biallelic.genotypes.chr{chrom}.ALL.vcf.bgz
  #   build: hg38
  #   filters: -i 'F_MISSING < 0.05 && FILTER = "PASS" && INFO/AF[0] >= 0.05 && INFO/AF[0] <= 0.95 && VFLAGS_One_subgroup = 0 && ABHet_One_subgroup > 0.25 && ABHet_One_subgroup < 0.75'

imputation:
  imputation:
    default:
      token: your_token_here 
  
  # Subject and variant level QC thresholds to apply before imputation
  preqc:
    hwe: 1e-20
    #Hardy-Weinberg Equilibrium Cutoff ("false" to skip)
    #MAF Cutoff ("false" to skip)
    maf: false
    #Variant level missingness cutoff
    geno: 0.05
    #Subject level missingness cutoff
    mind: 0.05
  
  # variant level QC thresholds to apply after imputation
  postqc:
    # MAF Cutoff between common and rare
    maf: 0.005
    # Rsq to use with common variants
    rsq: 0.3
    # Rsq to use with rare variants (set to NA to use rsq as hard cutoff)
    rsq2: NA
    # Number of SNPs of each type (Imputed, Typed) to sample for figures
    sampsize: 100000
  
  # Sample filtering
  
  chr_callrate: False
  chunk_callrate: True